reEmptyStringLeading = /\b__p \+= '';/g;
reEmptyStringMiddle = /\b(__p \+=) '' \+/g;
reEmptyStringTrailing = /(__e\(.*?\)|\b__t\)) \+\n'';/g;
reEscapedHtml = /&(?:amp|lt|gt|quot|#39);/g;
reUnescapedHtml = /[&<>"']/g;
reEscape = /<%-([\s\S]+?)%>/g;
reEvaluate = /<%([\s\S]+?)%>/g;
reInterpolate = /<%=([\s\S]+?)%>/g;
reIsDeepProp = /\.|\[(?:[^[\]]*|(["'])(?:(?!\1)[^\\]|\\.)*?\1)\]/;
reIsPlainProp = /^\w*$/;
reLeadingDot = /^\./;
rePropName = /[^.[\]]+|\[(?:(-?\d+(?:\.\d+)?)|(["'])((?:(?!\2)[^\\]|\\.)*?)\2)\]|(?=(?:\.|\[\])(?:\.|\[\]|$))/g;
reRegExpChar = /[\\^$.*+?()[\]{}|]/g;
reTrim = /^\s+|\s+$/g;
reTrimStart = /^\s+/;
reTrimEnd = /\s+$/;
reWrapComment = /\{(?:\n\/\* \[wrapped with .+\] \*\/)?\n?/;
reWrapDetails = /\{\n\/\* \[wrapped with (.+)\] \*/;
reAsciiWord = /[^\x00-\x2f\x3a-\x40\x5b-\x60\x7b-\x7f]+/g;
reEscapeChar = /\\(\\)?/g;
reEsTemplate = /\$\{([^\\}]*(?:\\.[^\\}]*)*)\}/g;
reFlags = /\w*$/;
reIsBadHex = /^[-+]0x[0-9a-f]+$/i;
reIsBinary = /^0b[01]+$/i;
reIsHostCtor = /^\[object .+?Constructor\]$/;
reIsOctal = /^0o[0-7]+$/i;
reIsUint = /^(?:0|[1-9]\d*)$/;
reLatin = /[\xc0-\xd6\xd8-\xf6\xf8-\xff\u0100-\u017f]/g;
reNoMatch = /($^)/;
reUnescapedString = /['\n\r\u2028\u2029\\]/g;
reHasUnicodeWord = /[a-z][A-Z]|[A-Z]{2,}[a-z]|[0-9][a-zA-Z]|[a-zA-Z][0-9]|[^a-zA-Z0-9 ]/;
/hasOwnProperty|(function).*?(?=\\\()| for .+?(?=\\\])/g;
interpolate = /{{([\s\S]+?)}}/g;
