/MMMM|MM|DD|dddd/g;
defaultDayOfMonthOrdinalParse = /\d{1,2}/;
/%d/i;
/%s/i;
formattingTokens = /(\[[^\[]*\])|(\\)?([Hh]mm(ss)?|Mo|MM?M?M?|Do|DDDo|DD?D?D?|ddd?d?|do?|w[o|w]?|W[o|W]?|Qo?|YYYYYY|YYYYY|YYYY|YY|gg(ggg?)?|GG(GGG?)?|e|E|a|A|hh?|HH?|kk?|mm?|ss?|S{1,9}|x|X|zz?|ZZ?|.)/g;
localFormattingTokens = /(\[[^\[]*\])|(\\)?(LTS|LT|LL?L?L?|l{1,4})/g;
/^\[|\]$/g;
/\\/g;
/\d/;
/\d\d/;
/\d{3}/;
/\d{4}/;
/[+-]?\d{6}/;
/\d\d?/;
/\d\d\d\d?/;
/\d\d\d\d\d\d?/;
/\d{1,3}/;
/\d{1,4}/;
/[+-]?\d{1,6}/;
matchUnsigned  = /\d+/;
matchSigned    = /[+-]?\d+/;
matchOffset    = /Z|[+-]\d\d:?\d\d/gi;
matchShortOffset = /Z|[+-]\d\d(?::?\d\d)?/gi;
matchTimestamp = /[+-]?\d+(\.\d{1,3})?/;
matchWord = /[0-9]{0,256}['a-z\u00A0-\u05FF\u0700-\uD7FF\uF900-\uFDCF\uFDF0-\uFF07\uFF10-\uFFEF]{1,256}|[\u0600-\u06FF\/]{1,256}(\s*?[\u0600-\u06FF]{1,256}){1,2}/i;
/\\(\[)|\\(\])|\[([^\]\[]*)\]|\\(.)/g;
/[-\/\\^$*+?.()|[\]{}]/g;
MONTHS_IN_FORMAT = /D[oD]?(\[[^\[\]]*\]|\s)+MMMM?/;
defaultLocaleMeridiemParse = /[ap]\.?m?\.?/i;
/define-locale/;
extendedIsoRegex = /^\s*((?:[+-]\d{6}|\d{4})-(?:\d\d-\d\d|W\d\d-\d|W\d\d|\d\d\d|\d\d))(?:(T| )(\d\d(?::\d\d(?::\d\d(?:[.,]\d+)?)?)?)([\+\-]\d\d(?::?\d\d)?|\s*Z)?)?$/;
basicIsoRegex = /^\s*((?:[+-]\d{6}|\d{4})(?:\d\d\d\d|W\d\d\d|W\d\d|\d\d\d|\d\d))(?:(T| )(\d\d(?:\d\d(?:\d\d(?:[.,]\d+)?)?)?)([\+\-]\d\d(?::?\d\d)?|\s*Z)?)?$/;
tzRegex = /Z|[+-]\d\d(?::?\d\d)?/;
/\d{4}-W\d\d/;
/\d{4}-\d\d/;
/\d{4}W\d{2}/;
aspNetJsonRegex = /^\/?Date\((\-?\d+)/i;
/^(?:(Mon|Tue|Wed|Thu|Fri|Sat|Sun),?\s)?(\d{1,2})\s(Jan|Feb|Mar|Apr|May|Jun|Jul|Aug|Sep|Oct|Nov|Dec)\s(\d{2,4})\s(\d\d):(\d\d)(?::(\d\d))?\s(?:(UT|GMT|[ECMP][SD]T)|([Zz])|([+-]\d{4}))$/;
/\([^)]*\)|[\n\t]/g;
/(\s\s+)/g;
/js-date/;
chunkOffset = /([\+\-]|\d\d)/gi;
aspNetRegex = /^(\-|\+)?(?:(\d*)[. ])?(\d+)\:(\d+)(?:\:(\d+)(\.\d*)?)?$/;
isoRegex = /^(-|\+)?P(?:([-+]?[0-9,.]*)Y)?(?:([-+]?[0-9,.]*)M)?(?:([-+]?[0-9,.]*)W)?(?:([-+]?[0-9,.]*)D)?(?:T(?:([-+]?[0-9,.]*)H)?(?:([-+]?[0-9,.]*)M)?(?:([-+]?[0-9,.]*)S)?)?$/;
/add-inverted-param/;
/dst-shifted/;
/\d{1,2}(th|st|nd|rd)/;
/\.?0+$/;
