/g/g;
CAMEL_CASE_REGEXP = /([A-Z])/g;
DASH_CASE_REGEXP = /-([a-z])/g;
/\n/g;
COMPONENT_REGEX = /%COMP%/g;
NS_PREFIX_RE = /^@([^:]+):(.+)/g;
NS_PREFIX_RE = /^@([^:]+):(.+)/g;
_cssImportRe = /@import\s+(?:url\()?\s*(?:(?:['"]([^'"]*))|([^;\)\s]*))[^;]*;?/g;
_urlWithSchemaRe = /^([a-zA-Z\-\+\.]+):/g;
CAMEL_CASE_REGEXP = /([A-Z])/g;
DASH_CASE_REGEXP = /-([a-z])/g;
/\W/g;
lre = /\[/g;
rre = /\]/g;
isRe = /\[is=([^\]]*)\]/g;
re = /([^:]*)(:*)(.*)/g;
_cssContentNextSelectorRe = /polyfill-next-selector[^}]*content:[\s]*?['"](.*?)['"][;\s]*}([^{]*?){/gim;
_cssContentRuleRe = /(polyfill-rule)[^}]*(content:[\s]*['"](.*?)['"])[;\s]*[^}]*}/gim;
_cssContentUnscopedRuleRe = /(polyfill-unscoped-rule)[^}]*(content:[\s]*['"](.*?)['"])[;\s]*[^}]*}/gim;
/::shadow/g;
/::content/g;
/\/shadow-deep\//g;
_shadowDeepSelectors = /(?:>>>)|(?:\/deep\/)/g;
_colonHostRe = /:host/gim;
_colonHostContextRe = /:host-context/gim;
_commentRe = /\/\*[\s\S]*?\*\//g;
_ruleRe = /(\s*)([^;\{\}]+?)(\s*)((?:{%BLOCK%}?\s*;?)|(?:\s*;))/g;
_curlyRe = /([{}])/g;
/[^a-zA-Z_]/g;
_SINGLE_QUOTE_ESCAPE_STRING_RE = /'|\\|\n|\r|\$/g;
_ASSET_URL_RE = /asset:([^\/]+)\/([^\/]+)\/(.+)/g;
_PATH_SEP_RE = /\//g;
INTERPOLATION_REGEXP = /\{\{([\s\S]*?)\}\}/g;
CR_OR_CRLF_REGEXP = /\r\n?/g;
HOST_REG_EXP = /^(?:(?:\[([^\]]+)\])|(?:\(([^\)]+)\)))$/g;
BIND_NAME_REGEXP = /^(?:(?:(?:(bind-)|(var-)|(let-)|(ref-|#)|(on-)|(bindon-))(.+))|\[\(([^\)]+)\)\]|\[([^\]]+)\]|\(([^\)]+)\))$/g;
